#pragma once

#define OPL_REG_ADDRESS 0x00
#define OPL_REG_DATA 0x10

#define OPL_SIZE_BLOCK_EXTENDED 0x16

#define OPL_ADDRESS_BASE_LEVELS 0x40
#define OPL_ADDRESS_BASE_F_NUMBER 0xa0
#define OPL_ADDRESS_BASE_KON_F_BLOCK 0xb0
#define OPL_ADDRESS_RHYTHM 0xbd
#define OPL_ADDRESS_BASE_FEEDBACK 0xc0

#define OPL_NUM_CHANNELS_MAX 11
#define OPL_NUM_CHANNELS_MELODY_MODE 9
#define OPL_NUM_OPERATORS 2
